name: Maximum Kampanya Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-campaigns:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies (geçici klasörde)
        run: |
          # Geçici klasöre geç
          cd /tmp
          npm init -y
          npm install puppeteer
          # Modülleri çalışma dizinine kopyala
          cp -r node_modules $GITHUB_WORKSPACE/
      
      - name: Run scraper
        run: node scraper.js
        continue-on-error: true  # Hata olsa bile devam et
      
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Sadece data klasörü ve screenshot'ları ekle
          git add data/ || true
          git add *.png || true
          # node_modules'i ekleme!
          git reset -- node_modules/ || true
          git reset -- package*.json || true
          # Değişiklik varsa commit et
          git diff --staged --quiet || git commit -m "🤖 Kampanya güncelleme: $(date +'%Y-%m-%d %H:%M')"
          git push || echo "Push başarısız, muhtemelen değişiklik yok"
